name: Build, Test, Migrate and Deploy ASP.Net Core app to Azure Web App - imageapi-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
  AZURE_BLOB_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test ImageApi.Tests/ImageApi.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish ImageApi/ImageApi.csproj -c Release -r win-x64 --self-contained false -o "${{ github.workspace }}/myapp"

      - name: Run EF migrations
        run: dotnet ef database update --project ImageApi/ImageApi.csproj

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1EDA5A4267444CC9D0525F52694B23B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_176E5C1BFBCE4DAC96F23A911255916C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6F3C8F534AA04DB8BF0C4AA15C7A92B0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'imageapi-service'
          slot-name: 'Production'
          package: .